### ISSUE TITLE
Story locking protocol

### ISSUE THREAD

**Issue by smashwilson** [smashwilson/collaborative-fiction#26]
Implement the story locking protocol. This ensures that at most one person can be contributing to a story at a time. Once a user *begins* to create a new Snippet and has a chance to see the previous Snippet, they are prevented from contributing again until at least one other user has advanced the story. This ensures that cheesing the contribution system by clicking contribute and then cancelling lets you see at most half of the story ahead of time.

**Comment by smashwilson** [comment]
Here's the general flow:

* `POST /story/:id/lock` to lock the story and access the prior snippet.
  * Attempt to acquire a lock on the story.
    * If no story exists with this ID, return a 404.
    * If the authenticated user doesn't have at least Contributor access to the story, return a 404.
    * If the authenticated user is not allowed to contribute because of a recent contribution, return a 403.
    * If the story is already locked by another user, and the lock has not expired, return a 409 with a response body that names the user and expiration timestamp.
    ```json
    {
      "lock": {
        "state": "denied",
        "owner": "otheruser",
        "expires": "Fri, 10 May 2015 17:58:28 +0000"
      }
    }
    ```
    * Otherwise, set the lock owner and expiration fields on the story to the current user and the current time plus a configurable expiry duration.
  * Record a contribution attempt by the current user on the story. The next possible contribution will be when the story has *n + 3* snippets: snippet *n* is the current one; snippet *n + 1* is the (potential) current contribution; *n + 2* ensures that a different user has a chance to contribute.
  * Insert the lock information into the story row, verifying that the tested preconditions remain true.
  * Return a 200 response containing information about the granted lock and the prior contribution on the story:
  ```json
  {
    "lock": {
      "state": "granted",
      "expires": "Fri, 10 May 2015 17:58:28 +0000"
    },
    "snippet": {
      "content": "..."
    }
  }
  ```
* `POST /snippets` with a `:story_id` in the request body to contribute a snippet.
  * If the `:story_id` does not exist, return a 404.
  * If the current user does not hold an unexpired lock on the story, return a 403.
  * Insert the new snippet with the current user and timestamp.
  * Revoke the story's lock.
  * Return a 204 to confirm acceptance of the snippet.
* `DELETE /story/:id/lock` to cancel an active contribution.
 * If no story exists with this ID, return a 404.
 * If the current user does not hold an unexpired lock on the story, return a 404.
 * Revoke the story's lock.
 * Return a 204 to confirm the lock's deletion.

**Comment by smashwilson** [comment]
The hard part here is going to be concurrency. If I ever want the ability to run multiple web heads, testing and setting the story lock needs to be an atomic operation.

Further reading: [concurrency control in PostgreSQL](http://www.postgresql.org/docs/9.5/static/mvcc-intro.html).

**Comment by smashwilson** [comment]
Complete :checkered_flag:

**Comment by rgbkrk** [comment]
:racehorse:
